name : uicraft
services:
  db:
    image: postgres:latest
    container_name: uicraft_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uicraft
    ports:
      - "5432:5432"